spring:
  datasource:
    url: jdbc:h2:mem:drivewise
    username: admin
    password:

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

  security:
    user:
      name: d4i
      password: 111